# Generated by Django 4.0.2 on 2022-02-27 12:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 12, 47, 21, 365672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 12, 47, 21, 366691, tzinfo=utc)),
        ),
    ]
