# Generated by Django 4.0.2 on 2022-03-05 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_comment_user_alter_blog_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_title',
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 5, 15, 46, 33, 886075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 5, 15, 46, 33, 886075, tzinfo=utc)),
        ),
    ]
